/ ------------------------------------------------------------------------------
/ Copyright (c) 2014, Marc J. Szalkiewicz
/ This file is part of frame.k.
/ This work is licensed under the Creative Commons Attribution-NonCommercial 4.0 International License.
/ To view a copy of this license, visit http://creativecommons.org/licenses/by-nc/4.0/
/ or send a letter to Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
/ ------------------------------------------------------------------------------
.librarian[`list`list]
compound:{{`$($~x),$y}/list[`a2l][x]}
